/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author Ruhon Borah
 */
public class jist_voting_log extends javax.swing.JFrame {

    /**
     * Creates new form jist_voting_log
     */
    public jist_voting_log() {
        // setUndecorated(true);
     //  setAlwaysOnTop(true);
      // setResizable(true);+
      
        
        
       // Toolkit tk= Toolkit.getDefaultToolkit();
        
      // int x=(int) tk.getScreenSize().getWidth();
      // int y=(int) tk.getScreenSize().getHeight();
        
        
        
      // this.setSize(x,y); 
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        untxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pf1 = new javax.swing.JPasswordField();
        showCheckbox = new javax.swing.JCheckBox();
        mxg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\JISTU ELECTION APPLICATION\\JIST LOGO.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(410, 20, 290, 190);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(370, 350, 26, 29);
        jPanel2.add(untxt);
        untxt.setBounds(470, 350, 270, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(310, 440, 140, 29);

        jButton1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(520, 530, 147, 40);

        jButton2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(690, 530, 150, 40);

        jButton3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(980, 0, 70, 40);

        msg.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jPanel2.add(msg);
        msg.setBounds(170, 590, 670, 40);

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("JISTSU VOTING APPLICATION");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(230, 220, 710, 50);

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("JORHAT INSTITUTE OF SCIENCE & TECHNOLOGY");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(140, 270, 820, 40);

        pf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf1ActionPerformed(evt);
            }
        });
        jPanel2.add(pf1);
        pf1.setBounds(470, 440, 270, 30);

        showCheckbox.setText("Show Password");
        showCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCheckboxActionPerformed(evt);
            }
        });
        jPanel2.add(showCheckbox);
        showCheckbox.setBounds(621, 480, 110, 23);
        jPanel2.add(mxg);
        mxg.setBounds(210, 580, 520, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String un=untxt.getText();
        String x=new String(pf1.getPassword());

        
        String sql="SELECT * FROM login WHERE id='"+un+"'AND PASSword='"+x+"'";
        String dbpass,dbun;
        dbpass="";
        dbun="";
        try
        {
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost/JISTSUE","root","rohan@#8011");
            Statement stat=con.createStatement();

            ResultSet rs=stat.executeQuery(sql);

            if(rs.next()){
                dbun=""+rs.getString("id");
                dbpass=""+rs.getString("PASSword");
                
                    if((un.equals(dbun))&&(x.equals(dbpass)))
                     {
                    new portal().setVisible(true);
        this.setVisible(false);
        }
       
       
       
            }
           else if ( untxt.getText().trim().isEmpty() && pf1.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "PLEASE INSERT ID AND PASSWORD");
              }
           else if ( untxt.getText().trim().isEmpty()){
                   JOptionPane.showMessageDialog(null, "PLEASE INSERT ID");
              }
           else if(pf1.getText().trim().isEmpty()){
                   JOptionPane.showMessageDialog(null, "PLEASE INSERT PASSWORD");
              }
             else{
            msg.setText("MESSAGE:INVALID USERNAME OR PASSWORD!");
               } 

        }catch(SQLException rs)
        {
            System.out.print(rs);

        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        untxt.setText("");
        pf1.setText("");
        msg.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void showCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCheckboxActionPerformed
        // TODO add your handling code here:
       if(showCheckbox.isSelected()){
           pf1.setEchoChar((char)0);
        }  else{
            pf1.setEchoChar('*');
        }
      

        
    }//GEN-LAST:event_showCheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jist_voting_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jist_voting_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jist_voting_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jist_voting_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jist_voting_log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel mxg;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JCheckBox showCheckbox;
    private javax.swing.JTextField untxt;
    // End of variables declaration//GEN-END:variables
}
